stages:
  - test

npm_test:
  stage: test
  tags:
    - docker
  image: node:alpine
  variables:
    FORCE_COLOR: "2"
  before_script:
    - apk --no-cache add make g++ gcc python3 linux-headers udev
  script:
    - npm ci
    - npm test

build_docker:
  stage: test
  tags:
    - shell
  variables:
    IMAGE_NAME: "ci:${CI_JOB_ID}"
  script:
    - ./.docker/build
    - docker rmi "$IMAGE_NAME"