#!/bin/bash
echo "Building for amd64"

echo "Executing docker build"

echo "DOCKERFILE_PATH=$DOCKERFILE_PATH"
echo "IMAGE_NAME=$IMAGE_NAME"

docker build \
    -t "$IMAGE_NAME" \
    --build-arg "NPM_TOKEN=$NPM_TOKEN" \
    .