#!/bin/bash
echo "Building for arm32"

echo "Downloading qemu"
curl -sSL `cat "$(dirname $0)/../qemu.url"` | tar xzvf - --strip-components=1

echo "Running multiarch/qemu-user-static:register"
docker run --rm --privileged multiarch/qemu-user-static:register --reset

echo "Preparing npmrc secret"
mkdir -p tmp && echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > tmp/npmrc

echo "Executing docker build"
docker build \
    -t "$IMAGE_NAME" \
    --secret id=npmrc,src=tmp/npmrc \
    .

rm -f tmp/npmrc